#!/bin/bash
#
# deploy an docker image to production
#
# Usage:
#  $ ./deploy jane:{sha}
# * image-id:  docker image id


if [ -z "$1" ] ; then
    echo "container ID required"
    exit 1
fi

echo "Deploying container: $1";
sleep $((RANDOM % 60)) ## mocking deployment
echo "Deployed successfully";
