name: add label to open issue
on:
  issues:
    types:
      - opened
jobs:
  label_issue:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello"
      - run: |
          gh issue edit $ISSUE_URL --add-label "bug"
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
          ISSUE_URL: ${{ github.event.issue.html_url }}

      - name: Add 'triage' label to new issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['triage']
            })
