name: build docker image
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - 'main'

jobs:
  build:
    name: build docker image
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # This would be uncommented on a proper pipeline and pushed to Jane image registry
      # - name: Login to Docker Hub
        # uses: docker/login-action@v3
        # with:
          # username: ${{ secrets.DOCKERHUB_USERNAME }}
          # password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: jane:${{ github.sha }}

      - name: deploy docker image
        run: ./script/deploy jane:${{ github.sha }}
