name: Issue Labeler

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  add-triage-label:
    runs-on: ubuntu-latest
    steps:
      - name: Add 'triage' label to new issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['triage']
            })
